- lib/utils.js
- test/test.utils.js
There have been some recent changes to the utils.js file in the google-api-nodejs-client repo. However, that file has been moved to this repo, and will soon be deleted from the original repo.
I am merging the exact same changes into this repo.
> Merging in changes from the google-api-nodejs-library repo

- lib/auth/jwtclient.js
- lib/auth/refreshclient.js
- package.json
- test/test.jwt.js
I switched the library to use [gtoken](https://github.com/ryanseys/node-gtoken) to add support for a path to a p12 keyfile. It's also a more well maintained and documented codebase (and made by the one and only @ryanseys).
I also caught a couple of bugs, which I will point out with comments.
(RE: https://github.com/GoogleCloudPlatform/gcloud-node/pull/458)
> Switch from GAPI to gtoken + Bug Fix

- README.md
Added an example similar to that found in the google-auth-library-ruby readme, also added the same Application Default Credentials section found there. A couple of other small cleanups.
> Added usage example to readme

- lib/auth/jwtclient.js
- test/test.jwt.js
When given a path to a keyfile, gtoken will update its own instance with the extracted email & key data after parsing it from the file. These values are useful to expose to users, as an example, for when [trying to create a signed URL for Storage access](https://github.com/stephenplusplus/gcloud-node/blob/spp--auth/lib/storage/file.js#L774-789).
Ping @ryanseys to see if this is a reliable way to get these values.
> update instance email & key properties from gToken

- lib/transporters.js
So this PR comes with a bit of confusion behind the responsibilities of the libraries in play. There's an issue [here](https://github.com/google/google-api-nodejs-client/issues/382) which I'm trying to address with this PR. However [google-api-nodejs-client](https://github.com/google/google-api-nodejs-client) where this code originated (which I maintain), still holds the tests that are associated with these line changes [here](https://github.com/google/google-api-nodejs-client/blob/master/test/test.transporters.js#L85). 
That is, I have to send a PR here, and update the tests on the other project. That's terrible, and not the way things should work. This is because the transporter for google-api-nodejs-client now just borrows this library's transporter [as seen …
> Do not set type on error object

- lib/transporters.js
- test/test.transporters.js
Certain API responses include an array of errors, rather than just one - e.g. https://cloud.google.com/compute/docs/reference/latest/regionOperations . Currently this throws a fairly useless error with an `undefined` message and an error code of `200`.
When `error.errors` is an array, this patch includes an error text with newline-joined messages from each individual error, the `code` from the first error, and an `errors` field with the underlying array of error objects.
> Create a meaningful error from response.error.errors array

- lib/transporters.js
- test/test.transporters.js
In the current setup, any response that contains a 'error' field gets interpreted as an Error, regardless of the status code. When this happens, any additional information in the response is discarded.
This change will prevent this when the status code is 200.
> Prevent status 200 responses from being reported as errors.

- lib/auth/oauth2client.js
- test/test.oauth2.js
Google used to use "accounts.google.com" as the ID token issuer and now is using "https://accounts.google.com" in its OpenId Connect spec compliant endpoints. Per https://developers.google.com/identity/protocols/OpenIDConnect?hl=en#sendauthrequest, both "accounts.google.com" and "https://accounts.google.com" should be accepted.
> Accept the new issuer value for Google ID tokens.

- lib/auth/computeclient.js
- test/test.compute.js
Use the `metadata.google.internal` instead of just `metadata`. This enables Compute Engine auth to work on Kubernetes, Container Engine,  and Container-Optimized VMs and setups with custom DNS servers. Otherwise, the DNS lookup for `metadata` will fail.
> Use full compute metadata DNS name

- lib/auth/googleauth.js
- test/test.compute.js
- test/test.googleauth.js
- test/test.iam.js
- test/test.jwt.js
- test/test.jwtaccess.js
- test/test.oauth2.js
- test/test.refresh.js
This fixes #78. Note that all of these changes except the one in `googleauth.js` are in test files, and none of these changes has any effect on the API surface
> Capitalize constructor names everywhere to satisfy linter

- package.json
Please update request:
✗ Medium severity vulnerability found on request@2.60.0
- desc: Remote Memory Exposure
- info: https://snyk.io/vuln/npm:request:20160119
- from: myproject > googleapis@7.1.0 > google-auth-library@0.9.8 > request@2.60.0
Your dependencies are out of date, otherwise you would be using a newer request than request@2.60.0.
https://snyk.io/vuln/npm:request:20160119
> Medium severity vulnerability

- lib/auth/googleauth.js
- test/fixtures/badlink
- test/fixtures/emptylink
- test/fixtures/goodlink
- test/test.googleauth.js
When using Kubernetes 1.3 secrets with Node.js the secret volume can be
a symbolic link to the credentials file. Previously, this would throw an
error due to the assertion of lstat.isFile(). This patch adds real path
resolution prior to asserting that filePath points to valid file.
> Handle symlinks to default application credentials

- lib/auth/oauth2client.js
- test/test.oauth2.js
Added support for array of multiple valid audiences to verify a Google
ID token.
Based on the support for similar functionality in the [Java library](https://developers.google.com/api-client-library/java/google-api-java-client/reference/1.20.0/com/google/api/client/googleapis/auth/oauth2/GoogleIdTokenVerifier.Builder#setAudience%28java.util.Collection%29)
> Added support for array of valid audiences

- lib/auth/googleauth.js
- lib/auth/jwtaccess.js
- lib/auth/jwtclient.js
- package.json
- test/fixtures/private2.json
- test/test.googleauth.js
Fixes google/google-auth-library-nodejs#97
```js
auth.getApplicationDefault(err, authClient) {
// ... 
});
```
```js
auth.getApplicationDefault(err, authClient, projectId) {
// ... 
});
```
> Add support for detecting project ID. Fixes #97

- CHANGELOG.md
- package.json
@tbetbetbe would you be able to do a release to npm? The google-cloud-node library needs this release for detecting a project ID in DAC environments. Hopefully this makes it easier!
> Prepare for 0.9.10 release

- lib/auth/oauth2client.js
- test/test.oauth2.js
It looks like #77 attempted to get this working, but didn't cover the case i've been running into. 
Here is the documentation for the error response from google drive: https://developers.google.com/drive/v3/web/handle-errors#401_invalid_credentials
If the failed 401 (or 403) request includes the error in the response body, it gets parsed by the transporter and passed back as an error to the callback. This prevents the token from being refreshed based on the current conditional logic.
I've fixed this by adding an exception for these errors. I've also added tests for `OAuth2Client#request()` based on the ones for `JWT#request()` and made sure to cover this case with a failing test before adding the fix.
Let me know if you need anything else.
> Fix oauth2 token refresh

- lib/auth/googleauth.js
- lib/auth/jwtclient.js
- lib/auth/oauth2client.js
- package.json
- test/test.googleauth.js
- test/test.jwt.js
- test/test.oauth2.js
Add fromAPIKey method to jwtClient and supporting
logic in oauth2client.js. Applying an API key to
an instance of the oauth2client will bypass token
checking/refresh and append the given API key as
a query string to each request made from the
instance in the following form:
```JS
`{target_base_url}?key={given_key}`
```
> Add API key support to Google-Auth-Library

- lib/auth/jwtaccess.js
- lib/auth/jwtclient.js
- lib/auth/oauth2client.js
- package.json
- yarn.lock
Lodash noop lib is useless and it's better to use just:
```js
var noop = Function;
```
Because of following reasons:
* It's shorter
* It's faster
* It doesn't take space in node_modules
* It will not fail in case of deletion of lodash.noop
* It will not take space in package.json and yarn.lock
* Even lodash devs removed lodash.noop from their code.
> Remove lodash.noop lib dependency

- lib/auth/googleauth.js
There was a typo in googleauth.js which prevented project ID caching
from working. Cache lookups were against `_cachedProjectID` but the
project ID was set to `_cahchedprojectID` when found.
> Fix project ID caching

- package.json
- ts/lib/auth/computeclient.ts
- ts/lib/auth/oauth2client.ts
- ts/lib/auth/refreshclient.ts
- ts/test/test.googleauth.ts
- ts/test/test.oauth2.ts
- ts/test/test.transporters.ts
- tslint.json
'variable-name' had to be disabled as this module has some public
members that don't follow the camelCase naming convention.
'no-duplicate-variable', 'no-unreachable' and 'label-undefined' are no
longer necessary as the compiler obviates these now.
This is dependent on #141.
> Add official tslint config

- package.json
- ts/lib/auth/jwtclient.ts
- ts/lib/auth/oauth2client.ts
* we were using lodash in tests even though we don't depend on it.
* clang-format was missing from package.json
> use correct dependencies

- package.json
- ts/lib/auth/computeclient.ts
- ts/lib/auth/oauth2client.ts
- ts/lib/auth/refreshclient.ts
- tsconfig.json
We now generate type definitions that can ship as part of the module.
This is indirectly dependent on #143, and those commits will show up here until that lands.
> Generate and export type definitions

- ts/lib/auth/oauth2client.ts
- ts/lib/transporters.ts
- ts/test/test.transporters.ts
At the moment, 4xx and 5xx responses are returned in
google-api-nodejs-client as regular responses, not errors. From the user
perspective, this is an odd pattern.
This commit forces 4xx and 5xx responses to be returned as errors, and
not be treated as a successful requests.
> Treat 4xx and 5xx responses as errors

- .gitignore
- package.json
- ts/lib/index.ts
- ts/test/test.index.ts
GoogleAuth is being exported as an ES6 class. This breaks compatibility
with existing JS users of this library for the main module export. This
change adds an index.js that re-exports GoogleAuth as a function.
Note that we are not using this hack for every single file in this
module. Anyone reaching into the internals of this module will need to
update their code.
> refactor: keep CommonJS compat for module

- ts/lib/auth/googleauth.ts
- ts/test/test.index.ts
Properly export DefaultTransport - some dependent libraries are using
this via loading an internal file.
> feature: export DefaultTransport

- package.json
Ensure that javascript output exist before the package gets published.
TBR=@justinbeckwith
> chore: add prepare script

- test/test.jwt.ts
Just a few more asserts to validate that #170 doesn't pop up.
> test: add asserts on authorize

- package-lock.json
- package.json
- src/auth/computeclient.ts
- src/auth/oauth2client.ts
- test/fixtures/kitchen/package.json
- test/fixtures/kitchen/src/index.ts
- test/fixtures/kitchen/tsconfig.json
- test/test.kitchen.ts
Adding a test to make sure the module works with TypeScript as expected.  Covers #177 and #178 and confuses me with #179.
> test: add typescript test

- src/auth/googleauth.ts
- src/index.ts
- test/fixtures/kitchen/src/index.ts
- test/test.compute.ts
- test/test.googleauth.ts
- test/test.iam.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
- test/test.oauth2.ts
- test/test.refresh.ts
When writing samples, I noticed that today I need to instantiate a new `GoogleAuth`, then from that instance you get access to the types needed to create new `JWT`, `UserRefreshClient`, and `OAuth2Client` objects.  That's silly.  Instead, I just added them to the exports on the index.
> BREAKING CHANGE: export class types and remove properties from GoogleAuth

- package-lock.json
- package.json
- src/auth/oauth2client.ts
- test/test.oauth2.ts
Includes an update to gtoken, where the same bug was fixed.
> fix: use urlencoded content-type for POST

- test/test.oauth2.ts
The tests for Node.js 4 and Node.js 6 randomly started failing due to what seems like a compiler change.  Our `package-lock.json` is pinning to `typescript@2.6.1`, which covers Node.js 8.  The `~2.6.0` tag in our `package.json` is letting new patch versions of typescript come through as designed, resulting in `typescript@2.6.2` getting installed.  I suspect TypeScript made a breaking change in a patch release :(
> fix: update code to support typescript@2.6.2

- src/auth/oauth2client.ts
Calling ```verifyIdToken```currently causes the following error:
```
Error: No pem found for envelope: Error: No pem found for envelope: {"alg":"RS256","kid":"0a50b51f9357c0045baa6a7c8cafbfa1604c0edb"}
at OAuth2Client.verifySignedJwtWithCerts (/root/node_modules/google-auth-library/src/auth/oauth2client.ts:670:5)
at OAuth2Client.<anonymous> (/root/node_modules/google-auth-library/src/auth/oauth2client.ts:563:24)
at OAuth2Client.<anonymous> (/root/node_modules/google-auth-library/src/auth/oauth2client.ts:563:24)
at step (/root/node_modules/google-auth-library/build/src/auth/oauth2client.js:57:23)
at Object.next (/root/node_modules/google-auth-library/build/src/auth/oauth2client.js:38:53)
at Object.next (/root/node_modules/google-auth-library/build/src/auth/oauth2client.js:38:53)
at …
```
> [oauth2client] Fixes mapping of FederatedSignonCertsResponse in verifyIdTokenAsync

- .gitignore
- README.md
- examples/adc.js
- examples/jwt.js
- examples/keepalive.js
- examples/oauth2.js
- package-lock.json
- package.json
- src/auth/oauth2client.ts
This includes a few things:
- Adds a few examples of using the API
- Improves the README
- ~~Update to a working version of gtoken~~ (handled in #203) 
- ~~Fixes a few bugs with Content-Type~~ (handled in #203) 
- ~~Exposes objects as exports instead of relying on public properties on the GoogleAuth object~~ (handled in #202)
> docs: add docs and samples

- README.md
- test/test.transporters.ts
The axios npm module supports setting an HTTP or HTTPS proxy via the http_proxy and https_proxy environment variables.  It also happens to be undocumented, which I didn't figure out until writing my own implementation  😂
Here I'm just adding a few tests, and updating our docs.  I will follow up with a PR against the axios docs to save others from my fate.  
Addresses #65.
> docs: document proxy behavior and verify with a test

- src/auth/oauth2client.ts
- test/test.oauth2.ts
> feat: allow passing maxExpiry to verifyIdToken

- README.md
- examples/refreshAccessToken.js
- src/auth/oauth2client.ts
- test/test.oauth2.ts
> chore: docs and samples for refresh token, update uris

- src/auth/googleauth.ts
- test/test.googleauth.ts
> fix: cache promise instead of ProjectId

- examples/adc.js
- examples/fromJSON.js
- examples/jwt.js
- examples/keepalive.js
- examples/oauth2-codeVerifier.js
- examples/oauth2.js
- examples/refreshAccessToken.js
- examples/verifyIdToken.js
An issue came up in #244 where the user is confused by the imported npm module.  I was previously reaching directly up to the index module, but with this fix we now will just use `npm link && npm link google-auth-library` to run the samples against the current working directory.
> fix: use npm link to run samples

- README.md
- examples/adc.js
- examples/fromJSON.js
- examples/keepalive.js
- src/index.ts
- test/test.googleauth.ts
> feat: export static GoogleAuth

- examples/verifyIdToken.js
examples/verifyIdToken.js uses the old signature for `OAuth2Client.verifyIdToken`, this PR upgrades it to the new API.
> Fix usage of OAuth2Client.verifyIdToken in example

- src/auth/computeclient.ts
- src/auth/googleauth.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- test/test.compute.ts
- test/test.googleauth.ts
- test/test.jwt.ts
- test/test.oauth2.ts
This pull request makes it possible to refresh the token when it is not expired but will expire in some period of time.
This can be used to address the issues described in #133, by allowing users to specify that tokens should be refreshed if they will expire soon. This is also necessary to fix GoogleCloudPlatform/cloud-profiler-nodejs#94
For earlier discussion of these changes, see PR #208.
> feat: Add ability to refresh token automatically before expiration.

- src/auth/loginticket.ts
I can't find the documentation that lists this field, but it is returned by the API.
> Add given_name and family_name to TokenPayload interface

- .gitignore
- examples/puppeteer/oauth2-test.js
- examples/puppeteer/package-lock.json
- examples/puppeteer/package.json
This was super fun!  Adds an example of using puppeteer to do automated testing of an OAuth2 workflow with Google Sign in. Addresses #225.
> chore: add example of puppeteer

- src/auth/computeclient.ts
- test/test.compute.ts
- test/test.googleauth.ts
When I try to use this library in an `npm` Container Builder step (via the [Cloud Storage API](https://cloud.google.com/storage/docs)), I get the following error:
```
{ Error: 404 page not found
at new RequestError (/workspace/functions/autodeploy/node_modules/google-auth-library/lib/transporters.js:34:42)
at Request._callback (/workspace/functions/autodeploy/node_modules/google-auth-library/lib/transporters.js:108:23)
at Request.self.callback (/workspace/functions/autodeploy/node_modules/request/request.js:186:22)
at emitTwo (events.js:126:13)
at Request.emit (events.js:214:7)
at Request.<anonymous> (/workspace/functions/autodeploy/node_modules/request/request.js:1163:10)
at emitOne (events.js:116:13)
at Request.emit (events.js:211:7)
at IncomingMessage.<anonymous> …
```
> Update token endpoint + fix failing tests

- examples/iap.js
- src/auth/jwtaccess.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
Adds support for additionalClaims to JWT, and an example of using it to work with the Identity Aware Proxy (IAP). Resolves #134  🤘
> feat: add IAP and additional claims support

- src/auth/googleauth.ts
- test/test.googleauth.ts
This change removes the not-private private function on GoogleAuth that was there only for testing purposes, and makes things a little easier to understand.
> chore: improve env var mocking

- src/auth/computeclient.ts
- test/test.compute.ts
This reverts commit 730d4b7d7de59b04862169fbc3a6feeab4d0debb. 
Turns out the GCF doesn't support the GCE metadata endpoint that includes /v1 👎 
Resolves #274 
Resolves #275
> Revert "fix: Update GCE metadata token endpoint (#269)"

- package-lock.json
- package.json
- src/auth/computeclient.ts
- src/auth/googleauth.ts
- test/test.compute.ts
- test/test.googleauth.ts
First draft of integrating the new and shiny gcp-metadata.  First https://github.com/stephenplusplus/gcp-metadata/pull/24 needs to land, and we need to ship it :)
Resolves #190.
> chore: use gcp-metadata

- src/auth/oauth2client.ts
- test/test.oauth2.ts
If users are calling `.request()` with a POST, and it's pushing a readableStream, we probably shouldn't retry the request.  This PR resolves #171, though we probably should eliminate this retry logic all up in 2.0.
> fix: do not retry if a post with readable stream

- package-lock.json
- package.json
- src/auth/computeclient.ts
- test/test.compute.ts
Resolves #283.
cc @stephenplusplus @jonparrott
> fix: retry connections to gce metadata server

- test/test.compute.ts
- test/test.googleauth.ts
- test/test.iam.ts
- test/test.index.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
- test/test.kitchen.ts
- test/test.loginticket.ts
- test/test.oauth2.ts
- test/test.refresh.ts
- test/test.transporters.ts
This change flattens out the structure of our tests, dropping the `describe` calls.  Doing this in preparation for a move over to ava, which doesn't support nested describe blocks.  Did a little cleanup along the way.
> test: flatten tests

- README.md
- src/auth/googleauth.ts
- test/test.googleauth.ts
BREAKING CHANGE:  Renames the `credential` field on the `ADCResponse` to `client`.  Previous code like this:
```js
const res = await auth.getApplicationDefault();	
const client = res.credential;	
```
Now will look like this:
```js
const res = await auth.getApplicationDefault();	
const client = res.client;	
```
Resolves #298.
> chore: rename `credential` to `client`

- .circleci/config.yml
- package.json
- tsconfig.json
BREAKING CHANGE: This change removes support for Node.js 4.x.  
Note sure if we want to put these changes in another branch or not.  (Probably a good idea)
> chore: drop support for node.js 4

- src/auth/googleauth.ts
- src/auth/iam.ts
- test/test.iam.ts
BREAKING CHANGE:  The `getRequestMetadata` of `IAMAuth` now directly returns http headers instead of requiring a callback function.
```js
IAMAuthClient.getRequestMetadata(null, (err, headers) => {
console.log(headers);
});
```
```js
const headers = IAMAuthClient.getRequestMetadata();
console.log(headers);
```
> chore: cleanup iam interface

- src/auth/oauth2client.ts
- test/test.compute.ts
Resolves #290. This is the one where retrying the request on 401/403 was causing all kinds of trouble.  After taking a closer look, I think we should keep the retries, but only in the situation where a user has set an access_token, a refresh_token, and they don't have an expiry_date.  This can happen if the user stashes a refresh and access token for later use, and then populates it manually at a later point.  That's the only real case I can think of where retrying getRequestMetadata is useful beyond what's there today.
> fix: limit situations where we retry

- package.json
- src/auth/computeclient.ts
- src/auth/credentials.ts
- src/auth/googleauth.ts
- src/auth/jwtaccess.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- src/transporters.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
BREAKING CHANGE:  Many methods that previously returned `null` may now return `undefined`. 
We had types that were optional or null all over the codebase.  Cleaned this up by removing any null type that was already optional.
> chore: prefer undefined over null

- README.md
- examples/keepalive.js
- package-lock.json
- src/auth/computeclient.ts
- src/auth/googleauth.ts
- src/auth/iam.ts
- src/auth/jwtaccess.ts
- src/auth/jwtclient.ts
- test/test.compute.ts
- test/test.googleauth.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
> feat: get rid of createScopedRequired

- src/auth/googleauth.ts
- test/test.googleauth.ts
Resolves #321 
Turns out that the GCE metadata server isn't picky about the trailing slash, but GCF is 🤷‍♂️
> fix: ensure GCF can read metadata requests

- src/transporters.ts
- test/test.transporters.ts
When deciding if we should add the google api user agent we were checking both the name *and* the value. In reality, we shouldn't duplicate the user-agent if the name matches, and the value doesn't.
> fix: don't duplicate user-agent

- src/auth/credentials.ts
- src/auth/jwtclient.ts
- test/test.jwt.ts
This fixes an issue where we look at the access_token instead of the id_token for IAP based requests.  The `any` will be resolved when https://github.com/google/node-gtoken/pull/59 lands. 
Resolves #327
> fix: use id_token for IAP requests

- README.md
- examples/jwt.js
- examples/oauth2.js
- package-lock.json
- src/auth/oauth2client.ts
- test/test.oauth2.ts
This adds a new `getTokenInfo` method to `OAuth2Client`, which calls the tokeninfo endpoint described here:
https://developers.google.com/identity/protocols/OAuth2UserAgent#validate-access-token
Resolves #336.
> feat: add getTokenInfo method

- src/transporters.ts
- test/test.transporters.ts
Resolves https://github.com/google/google-api-nodejs-client/issues/1083.
> fix: pin axios to nodejs

- README.md
- examples/keepalive.js
- package-lock.json
- package.json
- src/auth/googleauth.ts
- test/test.googleauth.ts
This change lets us stop pushing people towards createScopedRequired, while not breaking the API for those already using it.  It will also really simplify the getApplicationDefault scenario for users.
> feat: allow passing options to auth.getClient

- src/auth/googleauth.ts
- test/test.googleauth.ts
Another one that come up while trying to swap out google-auto-auth.  This way consumers can make a single call to get the client and make the request, with client caching.
> feat: add auth.request method

- README.md
- examples/refreshAccessToken.js
- src/auth/authclient.ts
- src/auth/computeclient.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- test/test.compute.ts
- test/test.jwt.ts
- test/test.oauth2.ts
Today we really have no way to tell users when their access_token was refreshed.  Some people store these on the server across multiple requests, so giving them some way to know when it happens would be nice.  Users are asking for this over in google-api-nodejs-client.  
Resolves #340.
> feat: emit an event when new tokens are obtained

- src/auth/oauth2client.ts
- test/test.oauth2.ts
The current `generateAuthUrl()` implementation allows for the `redirect_uri` opt to be overridden. Without the ability to specify the same override in the corresponding call to `getToken()`, the code exchange endpoint returns an error indicating a mismatch.
This change allows the `redirect_uri` and `client_id` used in the subsequent call to `getToken()` (and passed to the code exchange endpoint) to similarly be overridden.
A `redirect_uri` use case is straightforward, where a command line application (such as [clasp](https://github.com/google/clasp)) may wish to provide a localhost webserver to process the credentials returned from the code exchange endpoint, where the uri will contain a port number that was not known at the time the corresponding OAuth2Client was constructed. One current …
> Allow redirect_uri and client_id overrides in getToken opts

- src/auth/googleauth.ts
- test/test.googleauth.ts
In `google-auto-auth`, [credentials were being read before keyFilename](https://github.com/stephenplusplus/google-auto-auth/blob/master/index.js#L103).
I think in porting over features, that order was switched, so this PR switches it back.
> fix: read credentials field before keyFilename

- .circleci/config.yml
It never worked (wrong syntax, `requires` can be in workflow, not in a job description), but Circle never complained. Actually, it complained only when I tried to rerun something with SSH:
> chore: fix lint task in circle config

- src/auth/googleauth.ts
- src/auth/jwtclient.ts
- test/test.googleauth.ts
The idea is to replicate what's available [here](https://github.com/stephenplusplus/google-auto-auth/blob/master/index.js#L303).  It's used in nodejs-storage, and is blocking the integration of the new `nodejs-common` into `nodejs-storage`. 
@stephenplusplus I will admit that I don't entirely know what this is trying to do.  Can you walk us through the scenarios in how this is used?  
- Are you sure it belongs in the auth library, or does this belong in nodejs-common?
- Is this useful on anything *other* than a service account credential?  For example, does it make sense in the context of a Compute credential, or straight up OAuth2?
After we figure out where to stick this thing, I'll write tests 😆 
FYI @alexander-fenster @callmehiphop
> feat: add sign method to JWT

- README.md
- examples/compute.js
- package-lock.json
- src/auth/computeclient.ts
- test/test.compute.ts
This adds the ability to specify which service account the developer wants to use when using a `Compute` auth client.  This came up in the context of a missing tutorial.
> feat: enable custom service account with compute client

- .circleci/config.yml
- package.json
- tsconfig.json
BREAKING CHANGE: Node.js 4.x is no longer supported.
> fix: drop support for node.js 4.x

- package.json
- src/auth/computeclient.ts
- src/auth/oauth2client.ts
- test/test.compute.ts
- test/test.googleauth.ts
- test/test.oauth2.ts
**BREAKING CHANGE**:  The `OAuth2Client`, `JWT`, and `Compute` classes no longer accept parameters to override the authBaseUrl and tokenUrl.  These properties were largely available for testing, but there are better ways to test.  
```js
client = new OAuth2Client(CLIENT_ID, CLIENT_SECRET, REDIRECT_URI, {authBaseUrl, tokenUrl});	
```
```js
client = new OAuth2Client(CLIENT_ID, CLIENT_SECRET, REDIRECT_URI);	
```
> fix: use gcp-metadata for compute credentials

- package-lock.json
- src/auth/googleauth.ts
- src/auth/jwtaccess.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- src/transporters.ts
> fix: prevent unhandled rejections by avoid .catch

- package-lock.json
- package.json
- test/test.googleauth.ts
The `isAvailable` function no longer swallows unexpected errors which
means that we can start reporting better errors back to users of this
library.
Previously #398.
> chore: update gcp-metadata for isAvailable fix

- src/auth/computeclient.ts
- src/auth/iam.ts
- src/auth/jwtaccess.ts
- src/auth/jwtclient.ts
- src/messages.ts
- test/test.compute.ts
- test/test.iam.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
BREAKING CHANGE:  The `createScopedRequired` method has been deprecated on multiple classes.  The `createScopedRequired` and `createScoped` methods on the `JWT` class were largely in place to help inform clients when scopes were required in an application default credential scenario.  Instead of checking if scopes are required after creating the client, instead scopes should just be passed either into the `GoogleAuth.getClient` method, or directly into the `JWT` constructor.  
```js
auth.getApplicationDefault(function(err, authClient) {
if (err) {
return callback(err);
}
if (authClient.createScopedRequired && authClient.createScopedRequired()) {
authClient = authClient.createScoped([
'https://www.googleapis.com/auth/cloud-platform'
]);
}
callback(null, authClient);
});
```
```js
const …
```
> fix: deprecate the `createScopedRequired` methods

- package-lock.json
- src/auth/googleauth.ts
- src/auth/iam.ts
- src/auth/jwtaccess.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- src/messages.ts
- test/test.iam.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
- test/test.oauth2.ts
BREAKING CHANGE:  The `getRequestMetadata` method has been deprecated on the `IAM`, `OAuth2`, `JWT`, and `JWTAccess` classes.  The `getRequestHeaders` method should be used instead.  The methods have a subtle difference:  the `getRequestMetadata` method returns an object with a headers property, which contains the authorization header.  The `getRequestHeaders` method simply returns the headers.  
```js
const client = await auth.getClient();
const res = await client.getRequestMetadata();
const headers = res.headers;
```
```js
const client = await auth.getClient();
const headers = await client.getRequestHeaders();
```
> chore: deprecate getRequestMetadata

- README.md
- package.json
- src/transporters.ts
- test/test.transporters.ts
Uses [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent) to provide HTTPS proxy support, making up for the fact that axios doesn't support it natively yet.  
I don't have an HTTPS proxy sitting around where I can test this, so I am really throwing stuff at the wall here. 
Also of note - there is no reason I can possibly come up with why we would ever support an `HTTP` proxy.  Every endpoint we're going to hit for a Google service will be `HTTPS`, so I want to explicitly remove that from the documentation. 
Fixes #352
> fix: support HTTPS proxies

- src/auth/oauth2client.ts
reference: https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters
I'm not sure there is need test and how to test.
At this moment, my clients are using the option through casting as `any`.
> Update omitted parameter 'hd'

- README.md
`@google/repo check` found some errors.
> docs: replace google/ with googleapis/ in URIs

- src/auth/oauth2client.ts
- src/index.ts
I noticed that you're having to reach into files for types.  I should export them :)
https://github.com/googleapis/cloud-trace-nodejs/pull/871/files
> fix: export additional typescript types

- .compodocrc
- package.json
This is an experiment to use compdoc to see if we like it.  See:
https://googleapis.github.io/google-auth-library-nodejs/
> docs: add ref docs again

- src/index.ts
It would be good if users could refer to `GCPEnv` enumeration directly.
> fix(types): export GCPEnv type

- README.md
> docs: clarify access and refresh token docs

- .kokoro/browser-test.sh
- .kokoro/continuous/node8/browser-test.cfg
- .kokoro/presubmit/node8/browser-test.cfg
do not merge until `browser test` shows up in checks.
> build: add browser test running on Kokoro

- package.json
- src/auth/computeclient.ts
- src/auth/googleauth.ts
BREAKING CHANGE: In cases where the `Compute` client is used, the the `getRequestHeaders` method will no longer return an `AxiosResponse` object if a request is made to the metadata server.  The value of the object will return null. This is not likely to affect any downstream APIs, but is a breaking change nonetheless.
NOTE: This was already approved in https://github.com/googleapis/google-auth-library-nodejs/pull/536
> fix(deps): upgrade to gcp-metadata v0.9.3

- package.json
The new gtoken switched to gaxios, which means HTTPS proxies work!
(Next, we have to switch this library to gaxios)
> chore(deps): update gtoken

- package.json
- src/auth/authclient.ts
- src/auth/computeclient.ts
- src/auth/googleauth.ts
- src/auth/oauth2client.ts
- src/transporters.ts
- test/test.oauth2.ts
- test/test.transporters.ts
This switches from Axios to Gaxios. Hopefully nobody notices.
> refactor(deps): use `gaxios` for HTTP requests instead of `axios`

- src/auth/oauth2client.ts
If `OAuth2Client` without refresh token has no access token or has an expired access token, `OAuth2Client.prototype.getAccessToken` should throw an error.
This commit also reduces the number of unreachable code.
> fix: throw if there is no refresh token despite the necessity of refreshing

- src/crypto/browser/crypto.ts
> fix: avoid loading fast-text-encoding if not in browser environment

- src/auth/computeclient.ts
- src/auth/googleauth.ts
- src/auth/oauth2client.ts
Fixes #643.  This PR looks for multiple instances where context for exceptions could be lost.  The two primary types of cases here are:
1. Completely overwriting the error message but retaining the stack trace
2. Catching, and throwing an entirely new error with the original context lost
Instead, we always make sure to re-throw the original error, and consistently pin the original error message to the tail of the new message.
> fix: surface original stack trace and message with errors

- src/auth/googleauth.ts
- test/fixtures/private.json
- test/test.googleauth.ts
**BREAKING CHANGE** Currently, when a user is using application default credentials, and they call `auth.getProjectId`, we check a variety of sources, and return the first projectId we find.  In the event of none - we return `null`.  This PR changes the behavior, so instead of returning `null`, we throw an exception.
> fix: throw when adc cannot acquire a projectId

- src/auth/googleauth.ts
- test/fixtures/wellKnown.json
- test/test.googleauth.ts
This is *mostly* a test change.   `googleauth.ts` exposed a bunch of things purely for unit test mocking.  This change does a few things:
- Eliminates the "private" methods that were in place just for mocking
- Creates a clean slate in terms of env vars, file system, and OS before running an tests in the suite
- Moves to `sinon` to perform mocking instead of overwriting methods directly on the class instance
It uh, feels good.
> refactor: use sinon for mocking fs operations

- src/auth/computeclient.ts
- test/test.compute.ts
Fixes #532.  The original error message returned from the GCE metadata service was getting swallowed.  This ensures the underlying exception is thrown, and the message is preserved.
> fix: re-throw original exception and preserve message in compute client

- CHANGELOG.md
Fixes #613.  There were errors in the changelog in the 3.0 release.  I already cleaned up the release notes in the GitHub release.
> docs: fix the CHANGELOG to reflect 3.x breaking changes

- src/auth/oauth2client.ts
- test/test.oauth2.ts
Fixes #606.  In most cases, this library would throw if an attempt to refresh a token was made, and no refresh token was available.  It turns out there was a loophole here if the `getRequestHeaders` method was called, and the throw would get lost in the shuffle.  Instead, a call to the OAuth2 refresh endpoint would get made with an empty refresh token, leading to a less awesome exception.  This change:
- moves the place where we throw
- adds a test to verify the behavior
- Adds a `describe` block in the test file
Make sure to hide whitespace before reviewing this one :)
> fix: throw on missing refresh token in all cases

- package.json
- src/auth/computeclient.ts
- src/auth/googleauth.ts
- test/test.compute.ts
- test/test.googleauth.ts
The GCE metadata server is adding support for requesting tokens against user accounts with a predefined set of scopes.  This adds experimental support for passing the scopes as querystring parameters to the metadata service in compute credentials.
> feat: support scopes on compute credentials

- package.json
- src/auth/oauth2client.ts
- test/test.googleauth.ts
We have this thing called gRPC Fallback, which supports API keys and requires them to be sent in this special header `X-Goog-Api-Key`.  Some details [here](https://cloud.google.com/apis/docs/system-parameters) and more details - with JavaScript code sample I wrote - [here](https://googleapis.github.io/HowToRPC.html).
Let's set this header so that the [JavaScript code](https://github.com/googleapis/googleapis.github.io/blob/5d7c512d44e80f1abecd4e0bafb9ed7eb40168a3/examples/rpc/javascript/src/index.js#L49) could use `getRequestHeaders` in both service account and API key use cases.
> feat: use X-Goog-Api-Key header

- src/auth/computeclient.ts
- test/test.compute.ts
Fixes https://github.com/googleapis/nodejs-storage/issues/748
According to the requirements of the metadata server, this array of values was being parsed incorrectly by gaxios, which uses `querystring.stringify()`. The scopes query string parameter is expected as a comma-separated string value, as opposed to the `?scope=scope1&scopes=scope2` style that `querystring.stringify()` uses: https://cloud.google.com/functions/docs/securing/function-identity#access_tokens
> fix(compute): correctly specify scopes when fetching token

- README.md
The node module `opn` has been renamed to `open`, so I've changed the example to reflect that.
> docs: use `open` instead of `opn` in the README

- README.md
- samples/adc.js
- samples/credentials.js
- samples/headers.js
- samples/keepalive.js
- samples/keyfile.js
- src/auth/googleauth.ts
- test/test.googleauth.ts
BREAKING CHANGE: `getOptions()` no longer accepts GoogleAuthOptions, preventing a variety of side effects caused by credentials that have already been stored in cache. `new GoogleAuth({})` should instead be used to customize options, or to instantiate multiple clients. `fromJSON()` has also been made idempotent (it no longer changes the cache). 
fixes #390
> refactor!: getOptions() no longer accepts GoogleAuthOptions

- src/transporters.ts
- test/test.transporters.ts
After various discussions, where I ultimately landed was on:
1. keeping the `User-Agent` fields as they stand, as I've been assured that they won't interfere with the new `x-goog-api-client` header field.
2. introducing the new `x-goog-api-client` header to the auth client itself, putting us in the position to track information about folks using it directly.
> feat: populate x-goog-api-client header for auth

- package.json
- src/auth/envDetect.ts
- test/test.googleauth.ts
This pulls in an updated version of `gcp-metadata` which checks both IP and HOST; failing fast as soon as one of the endpoints fails to respond (this addresses issues with cloud run, vs., local environment).
Since only `gcpMetadata.isAvailable()` is currently fast pathed, this also performs a slight refactor on environment detection, we first detect `isComputeEngine()` hitting `isAvailable`, if we detect that we are in a compute engine environment, we next check if we're in kubernetes.
This results in one additional check, but improves cold-start performance in non-GCP environments drastically.
TODO: confirm with @JustinBeckwith, @stephenplusplus, etc., that `gcpMetadata.isAvailable()` is true for kubernetes.
> fix(deps): update to gcp-metadata and address envDetect performance issues

- CHANGELOG.md
- src/auth/oauth2client.ts
- src/messages.ts
- test/test.googleauth.ts
- test/test.oauth2.ts
In #575 @clocked0ne makes a case for it still being useful to be able to call `refreshAccessToken` in some circumstances; e.g., upstream errors our library does not yet take into account, but might be retriable.
We recently patched a [major issue with refreshing tokens](https://github.com/googleapis/google-auth-library-nodejs/pull/794), so it's my expectation that the only reason for calling `refreshAccessToken` would be edge-cases, but I agree with @clocked0ne that it's worth keeping this method available.
fixes #575
> feat: do not deprecate refreshAccessToken

- package.json
explicitly update to `gcp-metadata` version with `DEBUG_AUTH` option.
> fix(deps): updats to gcp-metadata with debug option

- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- test/test.oauth2.ts
It's highly unlikely, but the `expiry_date` could be wrong, or the comparison in `isTokenExpiring` could fail due to an inaccurate system clock. As a further fallback behavior, some developers may wish to opt-in to attempting a refresh if Google's servers respond with a status code that may indicate the token has expired.
> feat: adds forceRefreshOnFailure flag, for refreshing token on error

- src/transporters.ts
- test/test.transporters.ts
because options are passed by reference and not copied, a user specifying their own headers in gax options resulted in `x-goog-api-client` headers being appended multiple times.
fixes #819
> fix: don't append x-goog-api-client multiple times

- package.json
- src/auth/credentials.ts
- src/auth/googleauth.ts
- test/fixtures/.config/gcloud/application_default_credentials.json
- test/test.googleauth.ts
If the `quota_project` parameter is set, kicks it along in the request header `x-goog-user-project`.
> feat: set x-goog-user-project header, with quota_project from default credentials

- src/auth/credentials.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- test/fixtures/config-with-quota/.config/gcloud/application_default_credentials.json
- test/test.refresh.ts
The spec changed from quota_project to quota_project_id.
> fix: use quota_project_id field instead of quota_project

- src/auth/oauth2client.ts
- test/test.googleauth.ts
In writing smoke tests for [google-api-nodejs-client](https://github.com/googleapis/google-api-nodejs-client/pull/1889), I found that our apiary library uses the `requestAsync` code path, rather than the `getRequestHeaders` code path.
This PR:
* moves the logic for header population into `getRequestMetadataAsync`, which is called in both places.
* populates the header `requestAsync`.
* adds a regression test.
> feat: populate x-goog-user-project for requestAsync

- src/auth/oauth2client.ts
- src/index.ts
Fixes https://github.com/googleapis/google-api-nodejs-client/issues/1805
> fix(docs): improve types and docs for generateCodeVerifierAsync

- src/auth/authclient.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- test/fixtures/service-account-with-quota.json
- test/test.googleauth.ts
- test/test.jwt.ts
`quota_project_id` was not working for JWT clients, which are easier to test in our integration environment (which authenticates based on a service account, set in `GOOGLE_APPLICATION_CREDENTIALS`).
This PR:
1. pulls the logic for populating additional special headers into the `AuthClient` base class.
2. adds tests to make sure we're getting returned the types of client instances we expect, and that `x-goog-user-project` is populated for a `JWT` client.
> feat: make x-goog-user-project work for additional auth clients

- package.json
- src/auth/envDetect.ts
- test/test.googleauth.ts
This fixes failing tests caused by introducing caching to [gcp-metadata](https://github.com/googleapis/gcp-metadata/pull/274).
Taking a page fro `gcp-metadata`, this now also caches the promise returned by `getEnv` rather than its value, such that multiple libraries instantiated at the same time will not result in multiple enqueued promises.
> feat: cache results of getEnv()

- src/auth/computeclient.ts
- test/test.compute.ts
Fixes https://github.com/googleapis/google-auth-library-nodejs/issues/792#issuecomment-574555006 by adding `format=full` onto the metadata request.
The GCE metadata server in particular does not populate the `email` field of the ID Token JWT without it.
> fix: ensures GCE metadata sets email field for ID tokens

- src/auth/refreshclient.ts
- test/test.refresh.ts
If someone instantiates a UserRefreshClient directly, I couldn't see any reason to not set the refresh token, I confirmed that the client in turn refreshes on the first request.
fixes: #770
> fix: populate credentials.refresh_token if provided

- package.json
this should help mitigate the issue in #798, in practice throttled network requests seem to eventually complete successfully (it just takes much longer, e.g., 2.5 minutes for 150 concurrent requests in testing).
[gapic-generator-typescript#287](https://github.com/googleapis/gapic-generator-typescript/issues/287) proposes a better solution, which moves asynchronous logic away from the global scope.
> fix: if GCF environment detected, increase library timeout

- src/auth/googleauth.ts
- src/messages.ts
- test/test.googleauth.ts
We used to warn users when relying on a token provided by `gcloud auth application-default login`.  We are headed down a road where this is the default behavior (again), and probably don't need to warn users anymore.  Especially since the docs don't ask you to do it anymore.  
Fixes #833 somewhat bluntly
> fix: do not warn for SDK creds

- src/auth/oauth2client.ts
> fix(types): add additional fields to TokenInfo

- samples/signBlob.js
- samples/test/jwt.test.js
- src/auth/googleauth.ts
- test/test.googleauth.ts
> fix: use iamcredentials API to sign blobs

- package.json
- test/test.googleauth.ts
Arguably the upstream `gcp-metadata` change, which warns rather than throwing, was breaking ... but given that these should be rare events, and our default behavior is less user-hostile now, I'm voting that it's fine to simply update this test.
> fix: gcp-metadata now warns rather than throwing

- test/test.googleauth.ts
- test/test.jwt.ts
- test/test.oauth2.ts
The recent commit https://github.com/DefinitelyTyped/DefinitelyTyped/commit/e9103792668257b6cc86cd21d6c455ecb5fae1ea to `@types/node` makes `tsc` trigger "code unreachable" error. Fixing this with a workaround as suggested in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44944.
> fix: fixing tsc error caused by @types/node update

- src/auth/loginticket.ts
> fix(types): add locale property to idtoken

- src/auth/oauth2client.ts
[As code says](https://github.com/googleapis/google-auth-library-nodejs/blob/master/src/auth/oauth2client.ts#L1295), `audience` property is not mandatory on `OAuth2Client.prototype.verifyIdToken()` call despite the TypeScript interface currently requires it, so I have just updated the interface to make it optional.
> fix(tsc): audience property is not mandatory on verifyIdToken
