- lib/transporters.js
- test/test.compute.js
- test/test.jwt.js
First argument of request method is First argument of request method
must be url. And number of argument must be three.
> Add url parameter as request method.

- lib/auth/googleauth.js
- lib/auth/iam.js
- test/test.iam.js
> Adds an implementation of IAM credentials

- lib/auth/jwtclient.js
- test/test.jwt.js
> Corrects usage of refresh token in jwt client.

- lib/transporters.js
- test/test.transporters.js
> Fixed error code not being parsed correctly.

- .travis.yml
- package.json
Following google/google-api-nodejs-client#465
Async from 0.9.0 to 1.4.1 [Changelog](https://github.com/caolan/async/blob/master/CHANGELOG.md) - bug fixes and new features, no breaking changes
Request from 2.51.0 to 2.60.0 [Changelog](https://github.com/request/request/blob/master/CHANGELOG.md) - bug fixes
Thanks !
PS : I added node 0.12 and iojs for testing.
> Update async & request

- lib/auth/oauth2client.js
- test/test.jwt.js
> Make Oauth2Client#request retry on auth errors as documented

- lib/transporters.js
- test/test.transporters.js
Prevent User-Agent header from growing with each request.
Fixes #83
> Fix User-Agent header

- lib/auth/oauth2client.js
> Check that pem exists before verifying it.

- package.json
> Upgrade request to 2.74.x

- CHANGELOG.md
- package.json
@murgatroid99 @jayantkolhe I think this is what we need to be ready to roll as soon as we have push access to npmjs.
> Prepare for 0.9.9 release

- .travis.yml
- README.md
- package.json
Things were a bit out of date.
~~devDependencies can be addressed in a follow-on.~~
R= @jmdobry @jmuk
> update dependencies and add david-dm badge

- package.json
> bump jws version

- lib/auth/googleauth.js
- lib/auth/jwtaccess.js
- lib/auth/jwtclient.js
- lib/auth/refreshclient.js
- Replace all instances of `process.nextTick` with
`setImmediate`.
> Replace all instances of process.nextTick

- .clang-format
- gulpfile.js
- package.json
- ts/lib/auth/authclient.ts
- ts/lib/auth/computeclient.ts
- ts/lib/auth/googleauth.ts
- ts/lib/auth/iam.ts
- ts/lib/auth/jwtaccess.ts
- ts/lib/auth/jwtclient.ts
- ts/lib/auth/loginticket.ts
- ts/lib/auth/oauth2client.ts
- ts/lib/auth/refreshclient.ts
- ts/lib/transporters.ts
- ts/test/test.compute.ts
- ts/test/test.googleauth.ts
- ts/test/test.iam.ts
- ts/test/test.jwt.ts
- ts/test/test.jwtaccess.ts
- ts/test/test.loginticket.ts
- ts/test/test.oauth2.ts
- ts/test/test.refresh.ts
- ts/test/test.transporters.ts
This is dependent on #141 and #142.
> Apply official clang format style

- .gitignore
- package.json
- ts/lib/auth/authclient.ts
- ts/lib/auth/computeclient.ts
- ts/lib/auth/googleauth.ts
- ts/lib/auth/iam.ts
- ts/lib/auth/jwtaccess.ts
- ts/lib/auth/jwtclient.ts
- ts/lib/auth/loginticket.ts
- ts/lib/auth/oauth2client.ts
- ts/lib/auth/refreshclient.ts
- ts/lib/pemverifier.ts
- ts/lib/transporters.ts
- ts/test/test.compute.ts
- ts/test/test.googleauth.ts
- ts/test/test.iam.ts
- ts/test/test.jwt.ts
- ts/test/test.jwtaccess.ts
- ts/test/test.loginticket.ts
- ts/test/test.oauth2.ts
- ts/test/test.transporters.ts
- tsconfig.json
- yarn.lock
Trying to clean up the typing support here by enabling noImplicitAny on the compiler rules.
> enable noImplicitAny

- ts/lib/auth/authclient.ts
- ts/lib/auth/computeclient.ts
- ts/lib/auth/credentials.ts
- ts/lib/auth/googleauth.ts
- ts/lib/auth/iam.ts
- ts/lib/auth/jwtaccess.ts
- ts/lib/auth/jwtclient.ts
- ts/lib/auth/loginticket.ts
- ts/lib/auth/oauth2client.ts
- ts/lib/auth/refreshclient.ts
- ts/lib/index.ts
- ts/lib/pemverifier.ts
- ts/test/test.compute.ts
- ts/test/test.googleauth.ts
- ts/test/test.iam.ts
- ts/test/test.index.ts
- ts/test/test.jwt.ts
- ts/test/test.jwtaccess.ts
- ts/test/test.loginticket.ts
- ts/test/test.oauth2.ts
- ts/test/test.refresh.ts
The style guide disallow default exports.
> refactor: avoid default exports

- package-lock.json
- package.json
Fixes: https://github.com/google/google-auth-library-nodejs/issues/174
> chore: update gtoken to 1.2.3

- package-lock.json
- ts/lib/auth/oauth2client.ts
This is an updated version of #131  and #157 so we can clean up our PRs
> chore: address outdated PRs

- src/auth/googleauth.ts
- test/test.googleauth.ts
> chore: use gcloud config-helper to get projectId

- package-lock.json
- src/auth/authclient.ts
- test/test.oauth2.ts
> fix: add setCredentials method back to AuthClient

- package-lock.json
- src/auth/googleauth.ts
- test/test.googleauth.ts
> fix: retry checking isGCE

- test/test.oauth2.ts
This fixes #212, which adds test coverage for bug found by #211
> test: add test for verifyIdToken

- README.md
- examples/fromJSON.js
> docs: add example and readme for using fromJSON

- examples/oauth2-codeVerifier.js
- src/auth/oauth2client.ts
- src/index.ts
- test/test.oauth2.ts
Addresses #148.  We should land #215 first.
> feat: add support for code_verifier in getToken

- examples/adc.js
- examples/fromJSON.js
- examples/jwt.js
- examples/keepalive.js
- examples/oauth2-codeVerifier.js
- examples/oauth2.js
- examples/refreshAccessToken.js
- package-lock.json
- package.json
> chore: apply code style rules to javascript

- examples/jwt.js
- src/auth/computeclient.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- test/test.jwt.ts
- test/test.oauth2.ts
Should make #227 much more palatable.
> chore: accept options objects in constructors

- CHANGELOG.md
- CONTRIBUTORS
- README.md
relates to #252 
I've fixed the broken link in the readme, added to the changelog.md and contributors.md.
Thanks for letting me contribute 😄
> Fix samples/jwt.js link in README

- package-lock.json
- package.json
Draft notes here! 
https://github.com/google/google-auth-library-nodejs/releases/edit/untagged-5786fb09bb3c7ead3741
> chore: bump to 1.2.0

- package.json
Release notes drafted here:
https://github.com/google/google-auth-library-nodejs/releases/edit/untagged-8cf212199bb1562e9b9b
> chore: release 1.2.1

- test/test.googleauth.ts
- test/test.transporters.ts
Just trying to push the code coverage up a little bit at a time.
> test: improve coverage

- package.json
Release notes here:
https://github.com/google/google-auth-library-nodejs/releases/edit/untagged-e03a339494f8848de1cf
> chore: release 1.3.0

- package-lock.json
- package.json
Release notes: https://github.com/google/google-auth-library-nodejs/releases/edit/untagged-ef74c8e6310f923534c3
> chore: release 1.3.1

- README.md
> docs: add instructions for oauth2 and installed apps

- package-lock.json
- package.json
- src/auth/googleauth.ts
- test/test.googleauth.ts
I'm going to slowly move a fair bit of our mocking over sinon so we can take advantage of spies.  Already found a bug with it!
Resolves #302, and fixes the code coverage dip from #301
> chore: use sinon to mock in some cases

- package.json
Fixing up the random test failures happening in 4 and 6.
> fix: increase test timeout

- package-lock.json
- package.json
- src/auth/computeclient.ts
- src/auth/googleauth.ts
- src/auth/oauth2client.ts
- test/test.compute.ts
- test/test.googleauth.ts
- test/test.oauth2.ts
> chore: remove tokenUrl option

- package.json
Release notes:
https://github.com/google/google-auth-library-nodejs/releases/edit/untagged-4adf1ac433c7739500d0
> chore: release 1.3.2

- .circleci/config.yml
- .circleci/get_workflow_name.py
Setting up nightly builds workflow in the same (or similar) way as I did for Veneer libraries.
> chore: setup nightly builds workflow

- src/auth/computeclient.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- test/test.jwt.ts
- test/test.oauth2.ts
> fix: cache refreshToken promises

- .circleci/config.yml
- test/test.jwtaccess.ts
> chore: add nodejs 10 to test matrix

- package.json
[Release Notes](https://github.com/google/google-auth-library-nodejs/releases/tag/untagged-59331c38d7af1ce560f7)
> chore: release 1.5.0

- src/auth/googleauth.ts
- src/auth/jwtaccess.ts
- src/auth/jwtclient.ts
- src/auth/oauth2client.ts
- src/auth/refreshclient.ts
- test/fixtures/kitchen/tsconfig.json
- test/test.googleauth.ts
- test/test.jwt.ts
- test/test.jwtaccess.ts
- test/test.kitchen.ts
- test/test.oauth2.ts
- test/test.refresh.ts
> fix: do not use synthetic imports for nodejs core

- package.json
[Release Notes](https://github.com/google/google-auth-library-nodejs/releases/edit/untagged-db2831862c49feef26b3)
> chore: release 1.6.1

- package-lock.json
- test/test.googleauth.ts
Add a test for an behaviour we want to ensure.
> test: getDefaultProjectId should prefer config

- src/auth/googleauth.ts
The nested makes it hard to reason about what actually threw. See
https://github.com/googleapis/nodejs-logging-winston/issues/1#issuecomment-400640124
> cleanup: straighten nested try-catch

- package-lock.json
- src/auth/googleauth.ts
- src/messages.ts
- test/test.googleauth.ts
> fix: Warn when using user credentials from the Cloud SDK

- package-lock.json
- package.json
- src/auth/googleauth.ts
- test/test.googleauth.ts
> fix: surface file read stream errors

- package-lock.json
- src/index.ts
> nit: exports some interfaces

- README.md
- src/auth/googleauth.ts
> Update the url to application default credentials

- CHANGELOG.md
- package.json
- samples/package.json
> Release google-auth-library v2.0.1

- src/auth/oauth2client.ts
- test/test.oauth2.ts
> fix: use post for token revocation

- package.json
- test/test.googleauth.ts
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
> chore(deps): unpin sinon

- CHANGELOG.md
- package.json
- samples/package.json
This pull request was generated using releasetool.  Resolves #572
> Release google-auth-library v2.0.2

- src/auth/googleauth.ts
- test/test.googleauth.ts
This *should* fix an issue where firebase customers.  Resolves #359.
> fix: accept lowercase env vars

- package.json
- samples/oauth2-codeVerifier.js
> fix(deps): upgrade to the latest gaxios

- CHANGELOG.md
- package.json
- samples/package.json
> Release google-auth-library v3.0.1

- README.md
- browser-test/test.oauth2.ts
- samples/oauth2-codeVerifier.js
- samples/oauth2.js
- samples/puppeteer/oauth2-test.js
- samples/verifyIdToken.js
> docs: use the People API for samples

- src/auth/credentials.ts
- src/auth/googleauth.ts
- test/test.googleauth.ts
> feat: allow passing constructor options to getClient

- CHANGELOG.md
- package.json
- samples/package.json
> Release google-auth-library v3.1.0

- CHANGELOG.md
- package.json
- samples/package.json
> Release google-auth-library v3.1.1

- CHANGELOG.md
- package.json
- samples/package.json
> Release google-auth-library v3.1.2

- test/test.googleauth.ts
When running unit tests locally, I was getting failing tests if `GOOGLE_APPLICATION_CREDENTIALS` was set in my current session.  The unit test weren't properly faking those out.  This fixes that!
> test: harden tests to handle local logins

- test/test.googleauth.ts
The unit tests for `googleauth.ts` were picking and choosing where to quarantine environment variables.  This makes it really easy to forget a `blockGoogleApplicationEnvironmentVariables()` in new tests, and cause problems that only show up when the `GOOGLE_APPLICATION_CREDENTIALS` env var is set.  Instead - this change just *always* assumes a clean slate in terms of env vars.  
This is the first of a few clean up PRs that will be coming for the tests in this file to make it smaller, more reliable, and increase the coverage.
> refactor: always block env vars when running adc tests

- package.json
It's too late in London so Renovate bot is sleeping. So here I am with a manual dependency update!
> fix(deps): update dependency gtoken to v3

- src/auth/envDetect.ts
- test/test.googleauth.ts
> fix: use FUNCTION_TARGET to detect GCF 10 and above

- src/index.ts
see: https://github.com/googleapis/nodejs-googleapis-common/pull/154
> feat(types): expose ProjectIdCallback interface

- README.md
fixed naming of variable
Fixes #<issue_number_goes_here> (it's a good idea to open an issue first for discussion)
> fix(docs): fix variable name in README.md

- package.json
- src/auth/jwtclient.ts
see: https://github.com/googleapis/google-auth-library-nodejs/issues/774, https://github.com/googleapis/google-auth-library-nodejs/issues/575
> feat: if token expires soon, force refresh

- test/test.googleauth.ts
there's a race condition in our tests that sometimes crops up, this addresses it.
> test: address race condition in tests

- package.json
gaxios 2.1.0 resolves https://snyk.io/test/github/googleapis/google-auth-library-nodejs
> fix(deps): update gaxios dependency

- samples/verifyIdToken-iap.js
> docs(samples): fix verifyIdToken-iap sample

- README.md
> docs: update JWT sample
